### ISSUE TITLE
Cannot Install Foundry Module

### ISSUE THREAD

**Issue by zanychurch** [rpgxnihilo/lucky-flight-takedown#1]
Whenever I try to install the module, I get an error stating it's unable to load valid module manifest data.

**Comment by radoslawg** [comment]
I was about to report this issue. I wonder if something has changed in Foundry. In any case more details from console:

```
Error: Unable to load valid module manifest data from "https://github.com/rpgxnihilo/lucky-flight-takedown"
The requested manifest at "https://github.com/rpgxnihilo/lucky-flight-takedown" did not provide module manifest data.
    at Module.installPackage (/home/foundry/foundryvtt/resources/app/dist/packages/views.mjs:1:1634)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async SetupView.handlePost (/home/foundry/foundryvtt/resources/app/dist/server/views/setup.mjs:1:1980)

```

**Comment by Lamment** [comment]
I am having the same problem. Says the manifest wasnt provided.
